### ISSUE TITLE
Escape to exit map editor doesn't trigger editor-to-world conversion

### ISSUE THREAD

**Issue by vincent-uden** [vincent-uden/platform-c#48]

**Comment by sStellar** [comment]
Kan inte återskapa bugget, escape byter från map till spelet för mig.

**Comment by vincent-uden** [comment]
Ja det stämmer, men det är inte problemet. Problemet är att när den byter med Escape görs inte nya placerade rektanglar om till terräng i spelvärlden. För att enkelt återskapa det gör du följande:
1. Öppna map editorn
2. Placera en rektangel med Rect verktyget
3. Gå ur map editorn med Escape
Om man däremot går ut med F, kommer den nya rektangeln hamna i spelvärlden
